spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devcourse
    username: ENC(dNCKiAo9gisSxd5wvNLQuA==)
    password: ENC(FD9/5E10ecBzLLohqizj6zhaV9z3l62Q)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_KEY:testKey}

custom:
  base-path:
    image: ${IMAGE_PATH}
