global:
  scrape_interval: 5s # Prometheus가 metric 정보를 수집하는 주기

scrape_configs:
  - job_name: "prometheus" # 수행할 작업 이름
    static_configs:
      - targets:
          - "localhost:9090" # 요청을 보낼 host 정보

  - job_name: "springboot"
    metrics_path: "/actuator/prometheus" # metric 정보를 가져올 경로
    static_configs:
      - targets:
          - "host.docker.internal:8082"
